# Generated by Django 4.1.5 on 2023-01-29 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpostapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
