# Generated by Django 4.1.5 on 2023-01-30 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpostapp", "0002_blog_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="likes",),
        migrations.AddField(
            model_name="blog",
            name="favourite",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
