# Generated by Django 4.1.5 on 2023-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpostapp", "0005_remove_comment_email_remove_comment_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
