# Generated by Django 4.1.5 on 2023-02-10 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogpostapp", "0006_alter_comment_options_alter_comment_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
