# Generated by Django 4.1.5 on 2023-02-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpostapp", "0007_alter_blog_created_on_alter_comment_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
